package org.example.dataobject;

public class CanteenDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.id
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.name
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.imgurl
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.intro
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.id
     *
     * @return the value of canteen.id
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.id
     *
     * @param id the value for canteen.id
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.name
     *
     * @return the value of canteen.name
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.name
     *
     * @param name the value for canteen.name
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.imgurl
     *
     * @return the value of canteen.imgurl
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.imgurl
     *
     * @param imgurl the value for canteen.imgurl
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.intro
     *
     * @return the value of canteen.intro
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.intro
     *
     * @param intro the value for canteen.intro
     *
     * @mbg.generated Tue Nov 01 21:22:02 CST 2022
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}