package org.example.dataobject;

public class FoodDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.id
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.window
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer window;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.name
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.canteen_id
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer canteenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.calorie
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer calorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.avoidance
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer avoidance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.price
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.img_addr
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private String imgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.type
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.intro
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.id
     *
     * @return the value of food_item.id
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.id
     *
     * @param id the value for food_item.id
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.window
     *
     * @return the value of food_item.window
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getWindow() {
        return window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.window
     *
     * @param window the value for food_item.window
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setWindow(Integer window) {
        this.window = window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.name
     *
     * @return the value of food_item.name
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.name
     *
     * @param name the value for food_item.name
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.canteen_id
     *
     * @return the value of food_item.canteen_id
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getCanteenId() {
        return canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.canteen_id
     *
     * @param canteenId the value for food_item.canteen_id
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setCanteenId(Integer canteenId) {
        this.canteenId = canteenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.calorie
     *
     * @return the value of food_item.calorie
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getCalorie() {
        return calorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.calorie
     *
     * @param calorie the value for food_item.calorie
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setCalorie(Integer calorie) {
        this.calorie = calorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.avoidance
     *
     * @return the value of food_item.avoidance
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getAvoidance() {
        return avoidance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.avoidance
     *
     * @param avoidance the value for food_item.avoidance
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setAvoidance(Integer avoidance) {
        this.avoidance = avoidance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.price
     *
     * @return the value of food_item.price
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.price
     *
     * @param price the value for food_item.price
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.img_addr
     *
     * @return the value of food_item.img_addr
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.img_addr
     *
     * @param imgAddr the value for food_item.img_addr
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.type
     *
     * @return the value of food_item.type
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.type
     *
     * @param type the value for food_item.type
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.intro
     *
     * @return the value of food_item.intro
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.intro
     *
     * @param intro the value for food_item.intro
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}