package org.example.dataobject;

public class FoodDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.id
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.title
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.price
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.descrption
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private String descrption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.canteen
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private String canteen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.imgUrl
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_item.calorie
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    private Integer calorie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.id
     *
     * @return the value of food_item.id
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.id
     *
     * @param id the value for food_item.id
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.title
     *
     * @return the value of food_item.title
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.title
     *
     * @param title the value for food_item.title
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.price
     *
     * @return the value of food_item.price
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.price
     *
     * @param price the value for food_item.price
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.descrption
     *
     * @return the value of food_item.descrption
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public String getDescrption() {
        return descrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.descrption
     *
     * @param descrption the value for food_item.descrption
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setDescrption(String descrption) {
        this.descrption = descrption == null ? null : descrption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.canteen
     *
     * @return the value of food_item.canteen
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public String getCanteen() {
        return canteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.canteen
     *
     * @param canteen the value for food_item.canteen
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setCanteen(String canteen) {
        this.canteen = canteen == null ? null : canteen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.imgUrl
     *
     * @return the value of food_item.imgUrl
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.imgUrl
     *
     * @param imgurl the value for food_item.imgUrl
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_item.calorie
     *
     * @return the value of food_item.calorie
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public Integer getCalorie() {
        return calorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_item.calorie
     *
     * @param calorie the value for food_item.calorie
     *
     * @mbg.generated Sat Oct 29 20:38:20 CST 2022
     */
    public void setCalorie(Integer calorie) {
        this.calorie = calorie;
    }
}