package org.example.dataobject;

import java.util.Date;

public class JournalDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.id
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.uid
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.datetime
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    private Date datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.fid
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.calorie
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    private Integer calorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.price
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    private Integer price;

    private Integer meal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.id
     *
     * @return the value of journal.id
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.id
     *
     * @param id the value for journal.id
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.uid
     *
     * @return the value of journal.uid
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.uid
     *
     * @param uid the value for journal.uid
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.datetime
     *
     * @return the value of journal.datetime
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.datetime
     *
     * @param datetime the value for journal.datetime
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.fid
     *
     * @return the value of journal.fid
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.fid
     *
     * @param fid the value for journal.fid
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.calorie
     *
     * @return the value of journal.calorie
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public Integer getCalorie() {
        return calorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.calorie
     *
     * @param calorie the value for journal.calorie
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public void setCalorie(Integer calorie) {
        this.calorie = calorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.price
     *
     * @return the value of journal.price
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.price
     *
     * @param price the value for journal.price
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getMeal() {
        return meal;
    }

    public void setMeal(Integer meal) {
        this.meal = meal;
    }
}