package org.example.dao;

import org.example.dataobject.CanteenDO;

import java.util.List;

public interface CanteenDOMapper {
    List<CanteenDO> listCanteen();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbg.generated Fri Nov 04 13:38:06 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbg.generated Fri Nov 04 13:38:06 CST 2022
     */
    int insert(CanteenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbg.generated Fri Nov 04 13:38:06 CST 2022
     */
    int insertSelective(CanteenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbg.generated Fri Nov 04 13:38:06 CST 2022
     */
    CanteenDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbg.generated Fri Nov 04 13:38:06 CST 2022
     */
    int updateByPrimaryKeySelective(CanteenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbg.generated Fri Nov 04 13:38:06 CST 2022
     */
    int updateByPrimaryKey(CanteenDO record);
}