package org.example.dao;

import org.example.dataobject.FoodDO;

import java.util.List;

public interface FoodDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Tue Nov 01 12:01:37 CST 2022
     */
    List<FoodDO> listItem();
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Tue Nov 01 12:01:37 CST 2022
     */
    int insert(FoodDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Tue Nov 01 12:01:37 CST 2022
     */
    int insertSelective(FoodDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Tue Nov 01 12:01:37 CST 2022
     */
    FoodDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Tue Nov 01 12:01:37 CST 2022
     */
    int updateByPrimaryKeySelective(FoodDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Tue Nov 01 12:01:37 CST 2022
     */
    int updateByPrimaryKey(FoodDO record);
}