package org.example.dao;

import org.example.dataobject.FoodDO;
import org.example.service.model.FoodModel;

import java.util.List;

public interface FoodDOMapper {
    List<FoodDO> listFood();
    List<FoodDO> listFoodByCanteen(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    int insert(FoodDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    int insertSelective(FoodDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    FoodDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    int updateByPrimaryKeySelective(FoodDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_item
     *
     * @mbg.generated Fri Nov 04 15:01:27 CST 2022
     */
    int updateByPrimaryKey(FoodDO record);
}