package org.example.dao;

import org.example.dataobject.JournalDO;

import java.util.List;

public interface JournalDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    List<JournalDO> ListJournalByUsrId(Integer id);
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    int insert(JournalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    int insertSelective(JournalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    JournalDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    int updateByPrimaryKeySelective(JournalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated Tue Nov 08 00:49:25 CST 2022
     */
    int updateByPrimaryKey(JournalDO record);
}