package org.example.dao;

import org.example.dataobject.PasswordDO;

public interface PasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 02 14:27:31 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 02 14:27:31 CST 2022
     */
    int insert(PasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 02 14:27:31 CST 2022
     */
    int insertSelective(PasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 02 14:27:31 CST 2022
     */
    PasswordDO selectByPrimaryKey(Integer id);
    PasswordDO selectByUserId(Integer UserId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 02 14:27:31 CST 2022
     */
    int updateByPrimaryKeySelective(PasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Oct 02 14:27:31 CST 2022
     */
    int updateByPrimaryKey(PasswordDO record);
}